### ISSUE TITLE
Hook generation caused entire project to be regenerated

### ISSUE THREAD

**Issue by brane53** [feathers-plus/generator-feathers-plus#166] opened 2019-01-22 23:09 UTC
### SUMMARY

When I generate a hook for multiple services and choose the option `I will add the hook where its needed` my entire project gets regenerated. I'm actually not sure if that's normal, but my expectation would be that the hook file (along with its cooresponding test file) would be generated in `src/hooks` and `test/hooks` and that's it. I would have to manually add/remove it to *.hooks.ts . Instead it's regenerating all the files in the project.

Also, this may be another issue, but I tried freezing (for example) my *.service.ts files, but they still get regenerated.

Again... Normal? Not Normal? This doesn't appear to be normal to me.

### Steps to reproduce

1. run `feathers-plus g hook`
2. When asked if the hook will be used with a single service or multiple choose Multiple.
3. When asked which services the hook will be used with choose `I will add the hook where its needed`

### Output
```
$ feathers-plus g hook
  _____                  _     _
 |  ___|   ___    __ _  | |_  | |__     ___   _ __   ___     _
 | |_     / _ \  / _` | | __| | '_ \   / _ \ | '__| / __|  _| |_
 |  _|   |  __/ | (_| | | |_  | | | | |  __/ | |    \__ \ |_   _|
 |_|      \___|  \__,_|  \__| |_| |_|  \___| |_|    |___/   |_|


With contributions from: j2L4e, NickBolles, lukeburpee, Matt & Marshall

New features recently added:
- generate app: new prompts for test environments and seeding data.
- generate fakes: generate fake data for your services. Very powerful.
- generate hook: generate a hook for one or more services.
- generate test: generate a test for a hook, service or authentication.

Migrating app in dir alcomy-backend to latest cli+ version:
- Run npm update.

Using generator version 0.6.73
Source scan took 0s 129ms

? What is the name of the hook? restrictToFacility
? What is the name of the hook? restrictToFacility

We are updating the hook restrictToFacility in file restrict-to-facility.

? What is the name of the hook? restrict-to-facility
? The hook will be used with (Use arrow keys)
? The hook will be used with  Multiple services (src/hooks/)
? Which services will this hook be used with?
? Which services will this hook be used with?
  I will add the hook where its needed
     skip src\hooks\restrict-to-facility.ts
     skip .editorconfig
     skip .gitignore
     skip LICENSE
     skip README.md
     skip public\favicon.ico
     skip public\index.html
     skip test\app.test.ts
     skip src\refs\common.json
     skip src\seed-data.ts
     skip tsconfig.json
     skip tsconfig.test.json
     skip test\hooks\restrict-to-facility.unit.test.ts
     skip test\hooks\restrict-to-facility.unit.test.ts
     skip test\services\users.test.ts
     skip src\models\null.ts
     skip src\services\users\users.populate.ts
     skip test\services\organizations.test.ts
     skip src\models\null.ts
     skip src\services\organizations\organizations.populate.ts
     skip test\services\userOrganizations.test.ts
     skip src\models\null.ts
     skip src\services\userOrganizations\userOrganizations.populate.ts
     skip test\services\facilities.test.ts
     skip src\models\null.ts
     skip src\services\facilities\facilities.populate.ts
     skip test\services\facility-employees.test.ts
     skip src\models\null.ts
     skip src\services\facility-employees\facility-employees.populate.ts
    force package.json
    force config\default.json
    force nodemon.json
    force config\production.json
    force tslint.json
    force config\testing.json
    force src\hooks\log.ts
    force src\channels.ts
    force src\index.ts
    force src\app.hooks.ts
    force src\logger.ts
    force src\middleware\index.ts
    force src\app.ts
    force src\services\index.ts
    force src\app.interface.ts
    force src\typings.d.ts
    force src\services\users\users.service.ts
    force src\services\users\users.class.ts
    force src\services\users\users.interface.ts
    force src\services\users\users.schema.ts
    force src\services\users\users.mongo.ts
    force src\services\users\users.mongoose.ts
    force src\services\users\users.sequelize.ts
    force src\services\users\users.validate.ts
    force src\services\users\users.hooks.ts
    force src\services\organizations\organizations.service.ts
    force src\services\organizations\organizations.class.ts
    force src\services\organizations\organizations.interface.ts
    force src\services\organizations\organizations.schema.ts
    force src\services\organizations\organizations.mongo.ts
    force src\services\organizations\organizations.mongoose.ts
    force src\services\organizations\organizations.sequelize.ts
    force src\services\organizations\organizations.validate.ts
    force src\services\organizations\organizations.hooks.ts
    force src\services\userOrganizations\userOrganizations.service.ts
    force src\services\userOrganizations\userOrganizations.class.ts
    force src\services\userOrganizations\userOrganizations.interface.ts
    force src\services\userOrganizations\userOrganizations.schema.ts
    force src\services\userOrganizations\userOrganizations.mongo.ts
    force src\services\userOrganizations\userOrganizations.mongoose.ts
    force src\services\userOrganizations\userOrganizations.sequelize.ts
    force src\services\userOrganizations\userOrganizations.validate.ts
    force src\services\userOrganizations\userOrganizations.hooks.ts
    force src\services\facilities\facilities.service.ts
    force src\services\facilities\facilities.class.ts
    force src\services\facilities\facilities.interface.ts
    force src\services\facilities\facilities.schema.ts
    force src\services\facilities\facilities.mongo.ts
    force src\services\facilities\facilities.mongoose.ts
    force src\services\facilities\facilities.sequelize.ts
    force src\services\facilities\facilities.validate.ts
    force src\services\facilities\facilities.hooks.ts
    force src\services\facility-employees\facility-employees.service.ts
    force src\services\facility-employees\facility-employees.class.ts
    force src\services\facility-employees\facility-employees.interface.ts
    force src\services\facility-employees\facility-employees.schema.ts
    force src\services\facility-employees\facility-employees.mongo.ts
    force src\services\facility-employees\facility-employees.mongoose.ts
    force src\services\facility-employees\facility-employees.sequelize.ts
    force src\services\facility-employees\facility-employees.validate.ts
    force src\services\facility-employees\facility-employees.hooks.ts

```

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

### Expected behavior
For the project not to be regenerated. Only the hook and cooresponding test get created.

### Actual behavior
The entire project is gettign regenerated

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
@feathers-plus/cli 0.7.75
@feathers-plus/generator-feathers-plus 0.6.73
**NodeJS version**:
`v10.15.0`
**Operating System**:
Windows 10 Home (Version 1809) The latest October Update

**Comment by eddyystop** [comment] 2019-02-19 16:43
I feel I can close this as I think the issue is likely handled with no reply in 19 days.

**Closed by eddyystop** 2019-02-19 16:43 UTC
Labels: waiting for a reply

**Comment by brane53** [comment] 2019-02-28 22:26
@eddyystop Sorry for the extremely late reply. Regarding the freezing of modules. I think I'm doing what you're talking about. Here's my freeze configuration:

```
"freeze": [
      "src/services/users/users.service.ts",
      "src/services/user-organizations/user-organizations.service.ts",
      "src/services/organizations/organizations.service.ts",
      "src/services/facilities/facilities.service.ts",
      "src/services/facility-employees/facility-employees.service.ts",
      "src/services/organizations/organizations.validate.ts"
    ]
```

However, every one of those files is still being regenerated/overwritten.

**Comment by brane53** [comment] 2019-02-28 23:43
@eddyystop I just saw issue #220 and the pull request you made correcting this. Thank you!
